---
- name: Mkdir {{ docker_compose_eff_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ docker_compose_eff_install_dir }}'
    state: directory
    mode: '755'

- name: Downloading {{ docker_compose_url }} to {{ docker_compose_install_fq_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ docker_compose_url }}'
    dest: '{{ docker_compose_install_fq_exe }}'
    checksum: '{{ docker_compose_checksum }}'
    mode: '755'

- name: Linking {{ docker_compose_install_fq_link }} to {{ docker_compose_install_fq_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ docker_compose_install_fq_exe }}'
    dest: '{{ docker_compose_install_fq_link }}'
    state: link
